drop table IF EXISTS `pproc`;

create table `pproc` (
	`pid` int(11) NOT NULL AUTO_INCREMENT,
	`a-1` int(11) DEFAULT NULL,
	`a-2` int(11) DEFAULT NULL,
	`a-3` int(11) DEFAULT NULL,
	`b-1` int(11) DEFAULT NULL,
	`c-1` int(11) DEFAULT NULL,
	`c-2` int(11) DEFAULT NULL,
	`c-3` int(11) DEFAULT NULL,
	`c-4` int(11) DEFAULT NULL,
	`c-5` int(11) DEFAULT NULL,
	`d-1` int(11) DEFAULT NULL,
	`d-2` int(11) DEFAULT NULL,
	`d-3` int(11) DEFAULT NULL,
	`d-4` int(11) DEFAULT NULL,
	`d-5` int(11) DEFAULT NULL,
	`d-6` int(11) DEFAULT NULL,
	`d-7` int(11) DEFAULT NULL,
	`d-8` int(11) DEFAULT NULL,
	`d-9` int(11) DEFAULT NULL,
	`e-1` int(11) DEFAULT NULL,
	`e-2` int(11) DEFAULT NULL,
	`e-3` int(11) DEFAULT NULL,
	`e-4` int(11) DEFAULT NULL,
	`f-1` int(11) DEFAULT NULL,
	`f-2` int(11) DEFAULT NULL,
	`f-3` int(11) DEFAULT NULL,
	`f-4` int(11) DEFAULT NULL,
	`f-5` int(11) DEFAULT NULL,
	`f-6` int(11) DEFAULT NULL,
	`f-7` int(11) DEFAULT NULL,
	`f-8` int(11) DEFAULT NULL,
	`g-1` int(11) DEFAULT NULL,
	PRIMARY KEY (`pid`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
